language: python
python:
  - "3.6"
install:
  - pip install python-coveralls
script:
  - coverage run --source source cookiecutter setup.py test
branches:
  only:
    - master
after_success:
  - coveralls
